const teams2010_data = {
  'A': { teams: [
    { name: 'South Africa', players: ['Itumeleng Khune','Siboniso Gaxa','Tsepo Masilela','Matthew Booth','Morgan Gould','Lucas Thwala','Aaron Mokoena','Macbeth Sibaya','Kagisho Dikgacoi','Teko Modise','Siphiwe Tshabalala','Steven Pienaar','Richard Henyekane','Thembinkosi Fanteni','Benni McCarthy','Katlego Mphela','Bernard Parker'] },
    { name: 'Mexico', players: ['Guillermo Ochoa','Carlos Salcido','Ricardo Osorio','Jose Jonny Magallon','Aaron Galindo','Rafael Marquez','Gerardo Torrado','Pavel Pardo','Alberto Medina','Andres Guardado','Giovani Dos Santos','Guillermo Franco','Cuauhtemoc Blanco','Javier Hernandez','Carlos Vela','Aldo De Nigris','Miguel Sabah'] },
    { name: 'Uruguay', players: ['Fernando Muslera','Diego Lugano','Diego Godin','Maxi Pereira','Martin Caceres','Jorge Fucile','Bruno Silva','Walter Gargano','Cristian Rodriguez','Sebastian Eguren','Alvaro Pereira','Diego Perez','Nicolas Lodeiro','Edinson Cavani','Luis Suarez','Diego Forlan','Sebastian Abreu'] },
    { name: 'France', players: ['Hugo Lloris','Steve Mandanda','William Gallas','Eric Abidal','Bacary Sagna','Patrice Evra','Lassana Diarra','Jeremy Toulalan','Alou Diarra','Yoann Gourcuff','Florent Malouda','Franck Ribery','Sidney Govou','Nicolas Anelka','Thierry Henry','Karim Benzema','Andre-Pierre Gignac'] }
  ]},
  'B': { teams: [
    { name: 'Argentina', players: ['Sergio Romero','Martin Demichelis','Gabriel Heinze','Walter Samuel','Nicolas Otamendi','Javier Zanetti','Esteban Cambiasso','Fernando Gago','Javier Mascherano','Maxi Rodriguez','Juan Sebastian Veron','Angel Di Maria','Gonzalo Higuain','Sergio Aguero','Lionel Messi','Diego Milito','Carlos Tevez'] },
    { name: 'Nigeria', players: ['Vincent Enyeama','Joseph Yobo','Taye Taiwo','Obinna Nwaneri','Chidi Odiah','Onyekachi Apam','Danny Shittu','Ayila Yussuf','John Obi Mikel','Seyi Olofinjana','Kalu Uche','Peter Odemwingie','Nwankwo Kanu','Chinedu Obasi Ogbuke','Victor Obinna','Obafemi Martins','Yakubu Aiyegbeni'] },
    { name: 'South Korea', players: ['Lee Woon-Jae','Jung Sung-Ryong','Cho Yong-Hyung','Kang Min-Soo','Lee Jung-Soo','Kim Dong-Jin','Oh Beom-Seok','Lee Young-Pyo','Park Ji-Sung','Cho Won-Hee','Lee Chung-Yong','Ki Sung-Yueng','Kim Nam-Il','Kim Do-Heon','Seol Ki-Hyeon','Park Chu-Young','Lee Keun-Ho'] },
    { name: 'Greece', players: ['Alexandros Tzorvas','Sotirios Kyrgiakos','Vangelis Moras','Sokratis Papastathopoulos','Christos Patsatzoglou','Avraam Papadopoulos','Vasilis Torosidis','Georgios Seitaridis','Alexandros Tziolis','Angelos Basinas','Kostas Katsouranis','Giorgos Karagounis','Sotiris Ninis','Dimitris Salpingidis','Theofanis Gekas','Georgios Samaras','Angelos Charisteas'] }
  ]},
  'C': { teams: [
    { name: 'England', players: ['David James','John Terry','Rio Ferdinand','Glen Johnson','Ashley Cole','Matthew Upson','David Beckham','Frank Lampard','Steven Gerrard','Aaron Lennon','Gareth Barry','Shaun Wright-Phillips','Theo Walcott','Emile Heskey','Wayne Rooney','Jermain Defoe','Peter Crouch'] },
    { name: 'United States', players: ['Tim Howard','Carlos Bocanegra','Steve Cherundolo','Jay Demerit','Jonathan Bornstein','Jonathan Spector','Oguchi Onyewu','Michael Bradley','Ricardo Clark','Benny Feilhaber','Maurice Edu','Stuart Holden','Robbie Rogers','Clint Dempsey','Damarcus Beasley','Landon Donovan','Jozy Altidore'] },
    { name: 'Algeria', players: ['Faouzi Chaouchi','Lounes Gaouaoui','Anthar Yahia','Nadir Belhadj','Madjid Bougherra','Rafik Halliche','Hassan Yebda','Yazid Mansouri','Yacine Bezzaz','Khaled Lemmouchia','Karim Ziani','Mourad Meghni','Hameur Bouazza','Karim Matmour','Abdelkader Ghezzal','Rafik Saifi','Rafik Djebbour'] },
    { name: 'Slovenia', players: ['Samir Handanovic','Bostjan Cesar','Miso Brecko','Marko Suler','Bojan Jokic','Branko Ilic','Andraz Kirm','Robert Koren','Aleksandar Radosavljevic','Andrej Komac','Rene Krhin','Mirnes Sisic','Nejc Pecnik','Zlatan Ljubijankic','Valter Birsa','Milivoje Novakovic','Zlatko Dedic'] }
  ]},
  'D': { teams: [
    { name: 'Germany', players: ['Rene Adler','Tim Wiese','Per Mertesacker','Philipp Lahm','Heiko Westermann','Serdar Tasci','Arne Friedrich','Simon Rolfes','Michael Ballack','Thomas Hitzlsperger','Bastian Schweinsteiger','Piotr Trochowski','Mesut Ozil','Stefan Kiessling','Lukas Podolski','Miroslav Klose','Mario Gomez'] },
    { name: 'Australia', players: ['Mark Schwarzer','Scott Chipperfield','Lucas Neill','Patrick Kisnorbo','Rhys Williams','David Carney','Vincenzo Grella','Luke Wilkshire','Carl Valeri','Jason Culina','Mark Bresciano','Tim Cahill','Brett Holman','Brett Emerton','Harry Kewell','Joshua Kennedy','Scott McDonald'] },
    { name: 'Serbia', players: ['Vladimir Stojkovic','Nemanja Vidic','Branislav Ivanovic','Ivica Dragutinovic','Antonio Rukavina','Aleksandar Lukovic','Aleksandar Kolarov','Neven Subotic','Zdravko Kuzmanovic','Dejan Stankovic','Nenad Milijas','Milos Krasic','Gojko Kacar','Marko Pantelic','Milan Jovanovic','Nikola Zigic','Danko Lazovic'] },
    { name: 'Ghana', players: ['Richard Kingson','John Mensah','John Pantsil','Eric Addo','Harrison Afful','Samuel Inkoom','Hans Sarpei','Stephen Appiah','Michael Essien','Anthony Annan','Sulley Muntari','Kwadwo Asamoah','Haminu Dramani','Andre Ayew','Asamoah Gyan','Matthew Amoah','Dominic Adiyiah'] }
  ]},
  'E': { teams: [
    { name: 'Netherlands', players: ['Maarten Stekelenburg','Giovanni van Bronckhorst','Joris Mathijsen','John Heitinga','Andre Ooijer','Gregory van der Wiel','Mark van Bommel','Nigel de Jong','Demy de Zeeuw','Rafael van der Vaart','Wesley Sneijder','Ibrahim Afellay','Arjen Robben','Eljero Elia','Robin van Persie','Dirk Kuyt','Klaas-Jan Huntelaar'] },
    { name: 'Denmark', players: ['Thomas Sorensen','Daniel Agger','Lars Jacobsen','Simon Kjaer','Michael Jakobsen','William Kvist','Christian Poulsen','Michael Silberbauer','Daniel Jensen','Jakob Poulsen','Thomas Kahlenberg','Martin Jorgensen','Dennis Rommedahl','Jesper Gronkjaer','Soren Larsen','Nicklas Bendtner','Jon Dahl Tomasson'] },
    { name: 'Japan', players: ['Eiji Kawashima','Seigo Narazaki','Yuji Nakazawa','Marcus Tulio Tanaka','Atsuto Uchida','Yasuyuki Konno','Yuto Nagatomo','Yuki Abe','Hideo Hashimoto','Keisuke Honda','Makoto Hasebe','Kengo Nakamura','Daisuke Matsui','Yasuhito Endo','Shunsuke Nakamura','Shinji Okazaki','Yoshito Okubo'] },
    { name: 'Cameroon', players: ['Idriss Kameni','Rigobert Song','Andre Bikey','Geremi Njitap','Nicolas N\'Koulou','Benoit Assou-Ekotto','Alex Song','Stephane Mbia','Thimothee Atouba','Jean Makoun','Achille Emana','Landry N\'Guemo','Eyong Enoh','Somen Tchoyi','Paul Alo\'o Efoulou','Samuel Eto\'o','Achille Webo'] }
  ]},
  'F': { teams: [
    { name: 'Italy', players: ['Gianluigi Buffon','Fabio Cannavaro','Giorgio Chiellini','Fabio Grosso','Gianluca Zambrotta','Nicola Legrottaglie','Domenico Criscito','Angelo Palombo','Daniele De Rossi','Gennaro Gattuso','Andrea Pirlo','Claudio Marchisio','Mauro Camoranesi','Antonio Di Natale','Marco Borriello','Alberto Gilardino','Vincenzo Iaquinta'] },
    { name: 'Paraguay', players: ['Justo Villar','Denis Caniza','Paulo Da Silva','Julio Manzur','Julio Cesar Caceres','Dario Veron','Claudio Morel Rodriguez','Carlos Bonet','Cristian Riveros','Edgar Barreto','Enrique Vera','Victor Caceres','Jonathan Santana','Roque Santa Cruz','Nelson Valdez','Edgar Benitez','Oscar Cardozo'] },
    { name: 'New Zealand', players: ['Mark Paston','Ryan Nelsen','Ivan Vicelich','Ben Sigmund','Tony Lochhead','David Mulligan','Andrew Boyens','Tim Brown','Leo Bertos','Duncan Oughton','Jeremy Christie','Simon Elliott','James Pritchett','Chris Wood','Chris Killen','Shane Smeltz','Rory Fallon'] },
    { name: 'Slovakia', players: ['Jan Mucha','Martin Skrtel','Peter Pekarik','Jan Durica','Marek Cech','Zdeno Strba','Martin Petras','Vladimir Weiss','Marek Sapara','Miroslav Karhan','Jan Kozak','Marek Hamsik','Jan Novak','Robert Vittek','Erik Jendrisek','Stanislav Sestak','Filip Holosko'] }
  ]},
  'G': { teams: [
    { name: 'Brazil', players: ['Julio Cesar','Lucio','Juan','Luisao','Maicon','Dani Alves','Andre Santos','Josue','Gilberto Silva','Felipe Melo','Elano','Kaka','Ronaldinho','Robinho','Nilmar','Luis Fabiano','Adriano'] },
    { name: 'North Korea', players: ['Ri Myong-Guk','Ri Jun-Il','Cha Jong-Hyok','Ri Kwang-Chon','Pak Chol-Jin','Nam Song-Chol','Ji Yun-Nam','An Chol-Hyok','Ri Chol-Myong','Pak Nam-Chol','Mun In-Guk','An Yong-Hak','Kim Myong-Won','Kim Kum-Il','Hong Yong-Jo','Jong Tae-Se','Choe Kum-Chol'] },
    { name: 'Ivory Coast', players: ['Boubacar Barry','Kolo Toure','Emmanuel Eboue','Arthur Boka','Abdoulaye Meite','Souleymane Bamba','Siaka Tiene','Kanga Akale','Yaya Toure','Didier Zokora','Guy Demel','Romaric','Kader Keita','Gervinho','Bakari Kone','Salomon Kalou','Didier Drogba'] },
    { name: 'Portugal', players: ['Eduardo','Ricardo Carvalho','Bruno Alves','Pepe','Jose Bosingwa','Paulo Ferreira','Tiago Mendes','Duda','Raul Meireles','Joao Moutinho','Miguel Veloso','Deco','Nani','Simao','Cristiano Ronaldo','Liedson','Hugo Almeida'] }
  ]},
  'H': { teams: [
    { name: 'Spain', players: ['Iker Casillas','Carles Puyol','Gerard Pique','Sergio Ramos','Raul Albiol','Joan Capdevila','Alvaro Arbeloa','Sergio Busquets','Marcos Senna','Xavi Hernandez','Xabi Alonso','Jesus Navas','Cesc Fabregas','Andres Iniesta','David Silva','David Villa','Fernando Torres'] },
    { name: 'Switzerland', players: ['Diego Benaglio','Ludovic Magnin','Stephan Lichtsteiner','Stephane Grichting','Christoph Spycher','Philippe Senderos','Valon Behrami','Marco Padalino','Benjamin Huggel','Gokhan Inler','Tranquillo Barnetta','Gelson Fernandes','Hakan Yakin','Johan Vonlanthen','Alexander Frei','Blaise Nkufo','Eren Derdiyok'] },
    { name: 'Honduras', players: ['Noel Valladares','Maynor Figueroa','Osman Chavez','Victor Bernardez','Luis Ramos','Mauricio Sabillon','Wilson Palacios','Emilio Izaguirre','Amado Guevara','Ramon Nunez','Hendry Thomas','Danilo Elvis Turcios','Edgar Alvarez','Julio Cesar Leon','Carlos Pavon','David Suazo','Carlo Costly'] },
    { name: 'Chile', players: ['Claudio Bravo','Gonzalo Jara','Gary Medel','Waldo Ponce','Arturo Vidal','Ismael Fuentes','Mauricio Isla','Rodrigo Millar','Carlos Carmona','Roberto Cereceda','Marco Estrada','Matias Fernandez','Fabian Orellana','Alexis Sanchez','Mark Gonzalez','Humberto Suazo','Jean Beausejour'] }
  ]}
};
